apiVersion: v1
kind: Service
metadata:
  name: card-shows-service
spec:
  type: LoadBalancer
  selector:
    app: card-shows-app  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80 
